### ISSUE TITLE
No map shows up from openstreetmap

### ISSUE THREAD

**Issue by kleegrewec** [villaitatti/openstreetmap-app#1]
Hi all

I have problems integrating the opensteetmap application into researchspace. 

I followed the instructions for integrating openstreetmap in researchspace and have problems showing the results. In fact the screen remains empty after putting in a location name in the search field. I checked the example query from the researchspace documentation which worked fine as can be seen in figure 02.

My environment is docker basic and consists od the following containers:

kleegrewec@office-dev:basic> docker ps
CONTAINER ID   IMAGE                              COMMAND            CREATED          STATUS          PORTS                     NAMES
61c3d601d046   researchspace/platform-ci:latest   "/entrypoint.sh"   32 minutes ago   Up 16 minutes   0.0.0.0:10214->8080/tcp   basic_researchspace_1
6149ab5f1a62   researchspace/blazegraph:latest    "/entrypoint.sh"   43 minutes ago   Up 16 minutes   0.0.0.0:10215->8080/tcp   basic_blazegraph_1
6fa9fc024f0d   robcast/digilib:latest             "/entrypoint.sh"   43 minutes ago   Up 16 minutes   8080/tcp                  basic_digilib_1
kleegrewec@office-dev:basic> 
[210422_OpenStreetMapIntegration.log](https://github.com/villaitatti/openstreetmap-app/files/6357187/210422_OpenStreetMapIntegration.log)
![210422_OpenStreetMapIntegration_v01](https://user-images.githubusercontent.com/28925154/115692560-65331800-a35f-11eb-880e-1885fd595995.PNG)
![210422_OpenStreetMapIntegration_v02](https://user-images.githubusercontent.com/28925154/115692562-66644500-a35f-11eb-9be0-2eb5c06d8596.PNG)
![210422_OpenStreetMapIntegration_v03](https://user-images.githubusercontent.com/28925154/115692565-66fcdb80-a35f-11eb-9ee0-3659f330b863.PNG)

The log file attached contains the console output of the docker containers when running the application (template was renamed to OSM).
Figure 1 shows the application output.
Figure 2 shows the result of the query execution in sparql directly.  

Any idea what is going wrong here?
thanks, Christian

**Comment by gspinaci** [comment]
Hi!
RS is currently moving the open street map integration. I suggest taking a look at this PR https://github.com/researchspace/researchspace/pull/212. This PR has been approved, and it's going to be merged to master soon. The new OSM integration will come with three prefab templates.

Cheers

**Comment by kleegrewec** [comment]
Hi, thanks for taking care of this. I suppose it is up to me to wait until the changes are merged and the sample application repo was updated.

best, Christian
